name: Merge JSON Files & Update Location

on:
  schedule:
    - cron: '0 0 * * *'  # This runs at 00:00 UTC every day
  push:
    branches:
      - main  # Trigger on changes to the main branch
    paths:
      - '**/*.json'  # Trigger if any JSON files are changed
  workflow_dispatch:  # Allow manual triggers

jobs:
  merge-json:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonmerge requests retry

    - name: Create backup
      run: |
        cp data-siddiqui-family.json data-siddiqui-family.json.backup || true
        cp locations.json locations.json.backup || true

    - name: Run merge script
      run: python mergeJson.py  # First, run mergeJson.py to update data-siddiqui-family.json and locations.json

    - name: Validate JSON
      run: |
        python -c "import json; json.load(open('data-siddiqui-family.json')); json.load(open('locations.json'))"

    - name: Run update-location.py
      run: python update-location.py  # This will always run, regardless of changes

    - name: Commit merged files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data-siddiqui-family.json
        git add locations.json
        git commit -m "Update merged JSON files" -a || echo "No changes to commit"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  # Explicitly set your branch
